### ISSUE TITLE
new middleware: Post process getQueriesAgg

### ISSUE THREAD

**Issue by zallek** [botify-labs/botify-sdk-js-middlewares#2]

**Comment by kamalbennani** [comment]
# API V0 : 
## Request
Params
- size: "integer",

Body
```
{
    "query": []
}
```

## Response
Once the Data is being Received, we end up with this JSON object 
```json
[
 {
  "aggs": [],
  "count": "integer",
  "next": "string",
  "page": "integer",
  "prev": null,
  "results": [],
  "size" : "integer"
 }
]
```
'count' being the number of crawled url that match the query
aggs array of aggregation for example : 
```json
"aggs":[  
        {  
          "groups":[  
            {  
              "metrics":[  
                9947
              ],
              "key":[  
                200
              ]
            }
          ]
        }
      ]
``` 
as i noticed, there is not utility for params object, and also, when the data is sent to the browser, those attributes have always the same value 
```json
{
  "next": "?page=2",
  "page": "1",
  "prev": null,
  "results": [],
  "size" : "0"
}
```
When we send the same request without params data, we receive a good organised object with only necessary attributes that we need in order to display data in report.
#API V1  
## Response
```json
[  
  {  
    "status":200,
    "data":{  
      "count":10000,
      "aggs":[  
        {  
          "groups":[  
            {  
              "metrics":[  
                9947
              ],
              "key":[  
                200
              ]
            },
            {  
              "metrics":[  
                12
              ],
              "key":[  
                301
              ]
            },
            {  
              "metrics":[  
                12
              ],
              "key":[  
                302
              ]
            }
          ]
        }
      ]
    }
  }
]
```
You notice that we have a new attributes, which is status, as indicated by his name, it's returned for each query the status that correspond to it, as @zallek explain to me, in the previous version if one query breaks down, it's delete all the requests that we have submitted before which doesn't have any relation with the broken query.

**Comment by kamalbennani** [comment]
# Explain Object Transformation Process
## Re-indexation
```coffee
processResponse: (queryResponse) ->
        response = _.cloneDeep(queryResponse)
        if @_aggregates and @_aggregates.length
            treated_aggregators = {}
            for aggregator, i in @_aggregates
                treated_aggregators[aggregator.name] = aggregator.processResponse(queryResponse.aggs[i])
            response.aggs = treated_aggregators
        response
```
In this code, we re-index the aggregation, which is little bit strong, because the API return Objects in this format : 
```json
{
  "groupe": [
    {
      "key": [
        {}
      ], 
      "metrics": [
        {}
      ]
    }
  ]
}
``` 
and after doing this manipulation, we modify the object by wrapping it inside of an Array, and that what causes re-indexation : 
```json
[{
  "groupe": [
    {
      "key": [
        {}
      ], 
      "metrics": [
        {}
      ]
    }
  ]
}]
``` 
## Normalization and Adding Metadata when it's necessary
After Analyzing this code : 
```coffee
processResponse: (response_agg_object) ->
        json = { groups: [] }
        if response_agg_object
            json = _.cloneDeep response_agg_object
            # inject metadatas for group by ranges
            if json.groups
                group_by_list = []
                for group_by in json.groups
                    for key, i in group_by.key
                        # boolean key normalization
                        group_by.key[i] = @_normalizeBoolean(key)
                        # metadata injection
                        metadata = @_getRangeMetadata(key, i)
                        key.metadata = metadata if metadata
        json

    _getRangeMetadata: (range, groupByIndex) ->
        group_by = @_aggregate.group_by[groupByIndex]
        if typeof group_by == "object"
            for defined_range in group_by.ranges_list
                if defined_range.from == range.from and defined_range.to == range.to
                    return defined_range.metadata
        return false

    _normalizeBoolean: (val) ->
        return true if val == 'T'
        return false if val == 'F'
        val
```
We notice, that we Normalize Boolean Value, instead of having val = 'T' we return true and so one,
in second step, if we have a group by with rang attributes, we modify the object by adding metadata, otherwise, in simple case we do not modify the object

**Comment by zallek** [comment]
Differences in the top level structure (ie. `data/status`) is managed by batch middleware.

**Comment by zallek** [comment]
For transformations:
- normalizeBoolean: **keep it**
- getRangeMetadata: **keep it** and allow it also for **terms** group by
- Indexation of aggregates: **remove it** -> no sense

**Comment by zallek** [comment]
https://github.com/botify-labs/botify-sdk-js-middlewares/blob/master/docs/middlewares/getQueryAggregateMiddleware.md

**Comment by zallek** [comment]
New Models interface
```
Query(name)
addAggregate(aggregate)
getAggregates()
setFilters(filters)
getFilters()
getName()
toJsonAPI()
fromObject(object)

QueryAggregate(name)
addTermGroupBy(field, terms = [])
addGroupBy(field) // deprecated use addTermGroupBy(field) instead
addRangeGroupBy(field, ranges)
getGroupBys()
addMetric(operation, field)
getMetrics()
getName()
toJsonAPI()
```

**Comment by zallek** [comment]
Breaking Changes:
```
Query(name, query = {}) -> Query(name)                  // OK: second parameter was never used
Query.createAggregate: (name, aggregate = {}) ->  none  // TODO: use once
Query.getAggregate(name) -> Query.getAggregates()       // TODO
Query.toJSON() -> Query.toJsonAPI()                     // TODO: use once
Query.addField(field) -> none                           // OK: not used
Query.setFields(fields) -> none                         // OK: not used
Query.getFields() -> none                               // OK: not used
Query.addSort(sort) -> none                             // OK: not used
Query.setSorts(sorts) -> none                           // OK: not used
Query.getSorts() -> none                                // OK: not used
Query.processResponse()                                 // TODO: Result changed: terms keys are now turn into object

QueryAggregate(name, aggregate = {}) -> QueryAggregate(name)                             // OK: second parameter was never used
QueryAggregate.addGroupBy(field||QueryRangeGroupBy) -> QueryAggregate.addGroupBy(field)  // OK: giving a QueryRangeGroupBy wasn't used (though would be great to change to addTermGroupBy)
QueryAggregate.setGroupBy(group_by) -> none                                              // OK: wasn't used
QueryAggregate.getGroupBy() -> QueryAggrgeate.getGroupBys()                              // TODO: used once
QueryAggregate.setMetrics(group_by) -> none                                              // OK: wasn't used
QueryAggregate.toJSON() -> QueryAggregate.toJsonAPI()                                    // OK: wasn't used
```

**Comment by zallek** [comment]
Previous | New | State
------ | ------ | -------
Query(name, query = {}) | Query(name)                  | OK: second parameter was never used
Query.createAggregate: (name, aggregate = {}) |  none  | **TODO**: use once
Query.getAggregate(name) | Query.getAggregates()       | **TODO**
Query.toJSON() | Query.toJsonAPI()                     | **TODO**: use once
Query.addField(field) | none                           | OK: not used
Query.setFields(fields) | none                         | OK: not used
Query.getFields() | none                               | OK: not used
Query.addSort(sort) | none                             | OK: not used
Query.setSorts(sorts) | none                           | OK: not used
Query.getSorts() | none                                | OK: not used
Query.processResponse()   |                               | **TODO**: Result changed: terms keys are now turn into object
QueryAggregate(name, aggregate = {}) | QueryAggregate(name)                             | OK: second parameter was never used
QueryAggregate.addGroupBy(field or QueryRangeGroupBy) | QueryAggregate.addGroupBy(field)  | OK: giving a QueryRangeGroupBy wasn't used (though would be great to change to addTermGroupBy)
QueryAggregate.setGroupBy(group_by) | none                                              | OK: wasn't used
QueryAggregate.getGroupBy() | QueryAggrgeate.getGroupBys()                              | **TODO**: used once
QueryAggregate.setMetrics(group_by) | none                                              | OK: wasn't used
QueryAggregate.toJSON() | QueryAggregate.toJsonAPI()                                    | OK: wasn't used
